### ISSUE TITLE
a little misplacement of the text

### ISSUE THREAD

**Issue by MidNightCola** [dariolupo/Daze_Theme#10]
in the "edit game details" panel there are a few small problem

the delete is inside the ither icon in here
![Screenshot_20230210_032942](https://user-images.githubusercontent.com/77248142/218145664-8e13a36d-2fae-40c1-b021-d35eacb0a8f0.png)

and these 2 are not centered 
![Screenshot_20230210_033017](https://user-images.githubusercontent.com/77248142/218145810-0c905720-a728-44b7-88e0-102a958075ce.png)
![Screenshot_20230210_033124](https://user-images.githubusercontent.com/77248142/218145815-f1b0935d-2782-452d-8fcb-cc7cbef31ac3.png)
 
by the way the 2.0 update was perfect, thanks a lot for your effort

**Comment by dariolupo** [comment]
The first one should be already fixed with 2.1, I will look into the second for the next update

**Comment by dariolupo** [comment]
Fixed in 2.1.2
