### ISSUE TITLE
Background image not showing

### ISSUE THREAD

**Issue by heinkhant4ung** [dariolupo/Daze_Theme#11]
I really love this theme but I can't use it because of this problem. I've been having this issue since the theme was released but it looks like no one else is having this problem. I hope you can help me fix it.

![image](https://user-images.githubusercontent.com/125319778/218592229-f1cf8580-973a-4dd1-8ad9-5e06bd51436f.png)

**Comment by dariolupo** [comment]
Are you on the latest version? In that case you can use the [Theme Modifier ](https://github.com/Lacro59/playnite-thememodifier-plugin) plugin to enable the background picture in Details view. By default it's disabled by choice in the theme.

**Comment by heinkhant4ung** [comment]
Oh my god, thank you so much!
