### ISSUE TITLE
DataGrid style crashes Playnite

### ISSUE THREAD

**Issue by JosefNemec** [dariolupo/Daze_Theme#12]
To reproduce:  main menu -> configure emulators -> import -> scan some folder to import an emulator

![image](https://user-images.githubusercontent.com/3874087/219350506-57ea8605-3fe1-429d-9ef3-6aabf68a2e3d.png)

Most likely because you are referencing `White` instead of `WhiteColor` resource, but I haven't looked into it too deep.

**Comment by dariolupo** [comment]
Thanks for letting me know. Should be fixed in 2.1.1.
