### ISSUE TITLE
How to fix colours

### ISSUE THREAD

**Issue by tzmanish** [dariolupo/Daze_Theme#14]
Hey I messed up something

![image](https://user-images.githubusercontent.com/20627358/222783814-605d9b5a-0b6d-40a9-93ab-d7b214a85739.png)
![image](https://user-images.githubusercontent.com/20627358/222783888-946be1d3-a9ad-4e83-a126-1030412b7d05.png)
![image](https://user-images.githubusercontent.com/20627358/222784102-fb676697-67c4-4a44-bf2b-5ff4d288b043.png)
![image](https://user-images.githubusercontent.com/20627358/222784579-e9d7507f-aabc-4494-bb01-2ddd9cfb8c80.png)
![image](https://user-images.githubusercontent.com/20627358/222784628-c77a0003-6d83-4f07-8224-d284afbc0ade.png)

I tried reinstalling the theme, but that didn't fix it.

**Comment by dariolupo** [comment]
Hi! Try to go to the Theme Modifier settings, Constants tab (even if you can't see it, it should be the 3rd tab). Then scroll down where are the colors and click on the X next to each one of them. Save and see if this fixes it.

![image](https://user-images.githubusercontent.com/4670078/222799241-e0283354-0215-45f7-b1d3-accb3c9697e0.png)

**Comment by tzmanish** [comment]
Thank you very much, that worked :)
