### ISSUE TITLE
Star Rating On/Off

### ISSUE THREAD

**Issue by gerrykeys** [dariolupo/Daze_Theme#19]
Hello,

i know the possibility to disable the rating stars for the Grid view simply replacing the original template with the one that you posted in the Playnite forum.

Looking inside your template files, i found this code line in the Constants.xaml file:

```
 <!-- Star Rating ON/OFF -->
 <Visibility x:Key="StarsInGridView">Visible</Visibility>
```

It seems that the visibility of the rating for the Grid view is configurable.
Can you confirm this?
If yes, What kind of value i should put instead of "Visible"?
I tried with "False", "Invisible" and leaving empty value but nothing

**Comment by dariolupo** [comment]
Hi, you don't need to do that. Just download the latest version of the theme and in Playnite you can use the Theme Modifier add-on "Edit constants" tab to edit theme settings.
