### ISSUE TITLE
Star Rating settings

### ISSUE THREAD

**Issue by GhelloZ** [dariolupo/Daze_Theme#4]
is there a way to set the star rating based on community or critics scores instead of user score? IGDB and Universal Steam Metadata both import only those two so the star rating in the grid view always shows 0 stars
![immagine](https://user-images.githubusercontent.com/56313248/200352317-c04fce0b-eb1c-4f29-94db-dfa35585edc1.png)
A Short Hike and CyberPunk have the star rating because i manually set them

**Comment by dariolupo** [comment]
Looking at the Playnite documentation I don't think that's possible, will look into it but I doubt it.
