### ISSUE TITLE
Category panel

### ISSUE THREAD

**Issue by MidNightCola** [dariolupo/Daze_Theme#6]
since the border doesn't exist its not really apparent what the user should do

![Screenshot_20221206_021103](https://user-images.githubusercontent.com/77248142/205884336-d5004cc3-f9af-475a-b887-91565076ae82.png)

![Screenshot_20221206_021000](https://user-images.githubusercontent.com/77248142/205884273-65423489-945c-4ce8-8977-623f8637ec14.png)

**Comment by dariolupo** [comment]
Will have to check if I can enable it just for those sections, but not sure.

**Comment by dariolupo** [comment]
Improvements on this in 2.0.
