### ISSUE TITLE
Crown on complete games cover

### ISSUE THREAD

**Issue by noobguy233** [dariolupo/Daze_Theme#7]
Hii , i just wanted to say love you playnite theme and its amazing! 

There is just one thing that i wanted to ask you if you could make it that when completed games are in the cover if you could make a indication that they are completed ! Like a little 👑 on the buttom left or right Corner, that shows its done ! 
Thanks again!

**Comment by dariolupo** [comment]
Will look into this when I have some time :)

**Comment by noobguy233** [comment]
> Will look into this when I have some time :)

Thaaank yoou so much man !!! You amazing

**Comment by gandalfthegrayt** [comment]
Hello
would love to have this feature to.
Something that shows you 100% completed a game on the cover of the games 
Something similar to steam.
Also Thanks dariolupo

**Comment by dariolupo** [comment]
New version includes this.
