### ISSUE TITLE
Zoom panel collapsed setting not working

### ISSUE THREAD

**Issue by Eyji** [dariolupo/Daze_Theme#8]
Hello,

Thanks for the update.
I have successfully hidden the stars with the new constants.
However, the zoom panel (2) is not hiding even though I collapsed it as well. 

Bonus feedbacks: 

- I much preferred when the category (1) was transparent :) 
- The search bar is not rounded anymore :'( 
- I would gladly deactivate the bar at the bottom if you could add a way to use the icons elsewhere in the window

![image](https://user-images.githubusercontent.com/10639815/217962353-b3885ccc-265e-4aab-ac25-906451a09489.png)

**Comment by dariolupo** [comment]
Thanks for letting me know, will look into this!

**Comment by dariolupo** [comment]
Both are fixed in 2.1
