### ISSUE TITLE
Background image not showing after 1.1

### ISSUE THREAD

**Issue by Papitomalote** [dariolupo/Daze_Theme#9]
Hi, first of all thanks for the skin, the best looking one available in playnite.
After the 1.2 update, the background image doesn't show in details view. When I tick "Background Image" in the "Game fields to be displayed on details panel" it doesn't show the background image, in 1.1 version this worked. 

Thanks!

**Comment by dariolupo** [comment]
This was actually on purpose since the theme is mostly made to be used with blurred backgrounds from the settings. I'll see and check if I can add an option to enable the background image with ThemeModifier.

**Comment by dariolupo** [comment]
Added an option in 2.1!

**Comment by Papitomalote** [comment]
Thank you so much! Appreciate it

**Comment by heinkhant4ung** [comment]
I should've checked here first. I feel stupid now.
